# Generated by Django 6.0.1 on 2026-02-02 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='患者ID')),
                ('name', models.CharField(max_length=100, verbose_name='患者姓名')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='病案号')),
                ('gender', models.CharField(choices=[('Male', '男'), ('Female', '女')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='建档日期')),
                ('status', models.CharField(choices=[('已确认', '已确认'), ('待确认', '待确认')], default='待确认', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='记录ID')),
                ('visit_date', models.DateField(verbose_name='就诊日期')),
                ('treatment_stage', models.CharField(blank=True, max_length=100, verbose_name='治疗阶段')),
                ('clinical_diagnosis', models.TextField(blank=True, verbose_name='临床诊断')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '就诊记录',
                'verbose_name_plural': '就诊记录',
                'ordering': ['-visit_date'],
            },
        ),
    ]
