# Generated by Django 6.0.1 on 2026-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinical_diagnosis',
            field=models.TextField(blank=True, default='', verbose_name='临床诊断'),
        ),
    ]
