# Generated by Django 6.0.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_clinical_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitrecord',
            old_name='clinical_diagnosis',
            new_name='visit_notes',
        ),
    ]
