# Generated by Django 6.0.1 on 2026-02-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_visitrecord_clinical_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrecord',
            name='treatment_stage',
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='visit_notes',
            field=models.TextField(blank=True, verbose_name='就诊记录'),
        ),
    ]
