# Generated by Django 6.0.1 on 2026-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_visitrecord_treatment_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='completeness_score',
            field=models.IntegerField(default=0, help_text='0-100分，基于牙位图和影像文件', verbose_name='数据完整度评分'),
        ),
    ]
