# Generated by Django 6.0.1 on 2026-02-02 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='牙位图ID')),
                ('chart_data', models.JSONField(default=dict, help_text='存储牙齿状态（牙位编号、表面位置、颜色、符号）', verbose_name='牙位图数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '牙位图',
                'verbose_name_plural': '牙位图',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='影像ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.FileField(upload_to='imaging/%Y/%m/%d/', verbose_name='存储路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_files', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '影像资料',
                'verbose_name_plural': '影像资料',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
