# Generated by Django 6.0.1 on 2026-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingfile',
            name='series_name',
            field=models.CharField(blank=True, default='', help_text='用于标识 DICOM series，同一 series 的文件使用相同的名称', max_length=255, verbose_name='序列名称'),
        ),
    ]
