# Generated by Django 6.0.1 on 2026-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_imagingfile_series_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.CharField(help_text='用于存储在牙位图数据中的唯一标识，如 filled-resin', max_length=50, unique=True, verbose_name='标签ID')),
                ('label', models.CharField(help_text='前端显示的中文名称，如 充填(树脂)', max_length=50, verbose_name='显示名称')),
                ('label_type', models.CharField(choices=[('color', '颜色标记'), ('symbol', '符号标记')], max_length=10, verbose_name='标签类型')),
                ('value', models.CharField(help_text='存入 chart_data 的值，如 filled-resin', max_length=50, verbose_name='数据值')),
                ('color', models.CharField(blank=True, default='', help_text='仅颜色标记需要，如 #ef4444', max_length=20, verbose_name='颜色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '牙位图标签',
                'verbose_name_plural': '牙位图标签',
                'ordering': ['label_type', 'sort_order'],
            },
        ),
    ]
