# Generated by Django 6.0.1 on 2026-02-13 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_remove_visitrecord_treatment_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='标记ID')),
                ('content', models.TextField(verbose_name='标记内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotations', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '患者标记',
                'verbose_name_plural': '患者标记',
                'db_table': 'patient_annotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='回复ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='annotations.patientannotation', verbose_name='所属标记')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'verbose_name': '标记回复',
                'verbose_name_plural': '标记回复',
                'db_table': 'reply',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientannotation',
            index=models.Index(fields=['patient', '-created_at'], name='patient_ann_patient_a87ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['annotation', 'created_at'], name='reply_annotat_8ba6b6_idx'),
        ),
    ]
