# Generated by Django 6.0.1 on 2026-02-14 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientannotation',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_annotations', to=settings.AUTH_USER_MODEL, verbose_name='已查看用户'),
        ),
    ]
