# Generated by Django 6.0.1 on 2026-02-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户', 'verbose_name_plural': ' 用户'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=10, verbose_name='操作类型')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('object_id', models.CharField(max_length=255, verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='对象描述')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='变更内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_audit_user_id_0bc804_idx'), models.Index(fields=['model_name', 'created_at'], name='users_audit_model_n_a96760_idx')],
            },
        ),
    ]
