# Generated by Django 6.0.1 on 2026-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='首页布局配置'),
        ),
    ]
